apiVersion: v1
kind: Service
metadata:
  name: karsajobs-service
  namespace: default
spec:
  selector:
    app: karsajobs-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
