apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajobs-ui
  template:
    metadata:
      labels:
        app: karsajobs-ui
    spec:
      containers:
        - name: karsajobs-ui
          image: robifirmansyah/karsajobs-ui:latest
          ports:
            - containerPort: 8000
          env:
          - name: VUE_APP_BACKEND
            value: "http://localhost:30080"
